const now = new Date().toISOString();

export const SUPP_IDS = {
  magnesium: 'supp-mag-glyc',
  creatine: 'supp-creatine',
  vitD3: 'supp-vit-d3',
  omega3: 'supp-omega3',
  zinc: 'supp-zinc-pic',
  ashwagandha: 'supp-ashwa-ksm66',
  ltheanine: 'supp-l-theanine',
  coq10: 'supp-coq10-ubiq',
  vitK2: 'supp-vit-k2-mk7',
  iron: 'supp-iron-ferr-bis',
  vitC: 'supp-vit-c',
  b12: 'supp-b12-methyl',
  nac: 'supp-nac',
  berberine: 'supp-berberine-hcl',
  lionsMane: 'supp-lions-mane',
  melatonin: 'supp-melatonin',
  rhodiola: 'supp-rhodiola',
  collagen: 'supp-collagen-peptides',
  boron: 'supp-boron',
  turkeyTail: 'supp-turkey-tail',
} as const;

export const supplementsData = [
  { id: SUPP_IDS.magnesium, slug: 'magnesium-glycinate', name: 'Magnesium Glycinate', aliases: JSON.stringify(['magnesium glycinate', 'magnesium', 'mag glycinate']), category: 'mineral', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.creatine, slug: 'creatine-monohydrate', name: 'Creatine Monohydrate', aliases: JSON.stringify(['creatine', 'creatine mono']), category: 'amino_acid', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.vitD3, slug: 'vitamin-d3', name: 'Vitamin D3 (Cholecalciferol)', aliases: JSON.stringify(['vitamin d3', 'vit d3', 'd3']), category: 'vitamin', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.omega3, slug: 'omega-3-fish-oil', name: 'Omega-3 Fish Oil (EPA/DHA)', aliases: JSON.stringify(['omega 3', 'fish oil', 'epa dha']), category: 'fatty_acid', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.zinc, slug: 'zinc-picolinate', name: 'Zinc Picolinate', aliases: JSON.stringify(['zinc', 'zinc picolinate']), category: 'mineral', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.ashwagandha, slug: 'ashwagandha-ksm66', name: 'Ashwagandha KSM-66', aliases: JSON.stringify(['ashwagandha', 'ksm-66', 'ksm66']), category: 'adaptogen', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.ltheanine, slug: 'l-theanine', name: 'L-Theanine', aliases: JSON.stringify(['l-theanine', 'theanine']), category: 'amino_acid', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.coq10, slug: 'coq10-ubiquinol', name: 'CoQ10 (Ubiquinol)', aliases: JSON.stringify(['coq10', 'ubiquinol', 'coenzyme q10']), category: 'enzyme', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.vitK2, slug: 'vitamin-k2-mk7', name: 'Vitamin K2 (MK-7)', aliases: JSON.stringify(['vitamin k2', 'mk-7', 'mk7']), category: 'vitamin', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.iron, slug: 'iron-ferrous-bisglycinate', name: 'Iron (Ferrous Bisglycinate)', aliases: JSON.stringify(['iron', 'ferrous bisglycinate', 'gentle iron']), category: 'mineral', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.vitC, slug: 'vitamin-c', name: 'Vitamin C (Ascorbic Acid)', aliases: JSON.stringify(['vitamin c', 'vit c', 'vitc', 'ascorbic acid', 'ascorbate']), category: 'vitamin', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.b12, slug: 'vitamin-b12-methylcobalamin', name: 'Vitamin B12 (Methylcobalamin)', aliases: JSON.stringify(['b12', 'vitamin b12', 'methylcobalamin', 'methyl b12', 'methyl-b12']), category: 'vitamin', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.nac, slug: 'nac', name: 'NAC (N-Acetyl Cysteine)', aliases: JSON.stringify(['nac', 'n-acetyl cysteine', 'n acetyl cysteine', 'n-acetylcysteine', 'acetyl cysteine']), category: 'amino_acid', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.berberine, slug: 'berberine-hcl', name: 'Berberine HCl', aliases: JSON.stringify(['berberine', 'berberine hcl', 'berberin', 'berberine hydrochloride']), category: 'botanical', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.lionsMane, slug: 'lions-mane', name: "Lion's Mane Mushroom", aliases: JSON.stringify(["lion's mane", 'lions mane', 'hericium erinaceus', 'lions mane mushroom']), category: 'mushroom', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.melatonin, slug: 'melatonin', name: 'Melatonin', aliases: JSON.stringify(['melatonin', 'mel', 'sleep hormone']), category: 'hormone', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.rhodiola, slug: 'rhodiola-rosea', name: 'Rhodiola Rosea', aliases: JSON.stringify(['rhodiola', 'rhodiola rosea', 'golden root', 'arctic root', 'rosavin']), category: 'adaptogen', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.collagen, slug: 'collagen-peptides', name: 'Collagen Peptides', aliases: JSON.stringify(['collagen', 'collagen peptides', 'hydrolyzed collagen', 'bovine collagen', 'marine collagen']), category: 'protein', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.boron, slug: 'boron', name: 'Boron', aliases: JSON.stringify(['boron', 'boron citrate', 'boron supplement']), category: 'mineral', status: 'published', createdAt: now, updatedAt: now },
  { id: SUPP_IDS.turkeyTail, slug: 'turkey-tail', name: 'Turkey Tail Mushroom', aliases: JSON.stringify(['turkey tail', 'trametes versicolor', 'turkey tail mushroom', 'polypore']), category: 'mushroom', status: 'published', createdAt: now, updatedAt: now },
];

export const scienceData = [
  {
    id: 'sci-mag',
    supplementId: SUPP_IDS.magnesium,
    summary: 'Bioavailable magnesium form commonly used for sleep and relaxation support.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Sleep support', detail: 'RCTs suggest magnesium can improve sleep quality in deficient adults.', citation: 'PMID: 23853635', quality: 'high' },
      { title: 'Anxiety support', detail: 'Systematic review found magnesium may help mild anxiety.', citation: 'PMID: 28445426', quality: 'medium' },
    ]),
    interactions: JSON.stringify([{ label: 'Zinc', severity: 'moderate', note: 'Space high-dose mineral supplements by 2+ hours.' }]),
    sideEffects: JSON.stringify([{ label: 'GI discomfort', incidence: 'low', mitigation: 'Take with food or at bedtime.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Tetracycline antibiotics', severity: 'high', mechanism: 'Chelation reduces antibiotic absorption.', recommendation: 'Separate by 2-4 hours.' }]),
  },
  {
    id: 'sci-creatine',
    supplementId: SUPP_IDS.creatine,
    summary: 'Well-studied performance supplement with strong safety profile at maintenance doses.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Strength and lean mass', detail: 'Meta-analyses show improved strength outcomes with training.', citation: 'PMID: 18091016', quality: 'high' },
      { title: 'Cognitive resilience', detail: 'Some studies suggest benefit during sleep deprivation.', citation: 'PMID: 15531663', quality: 'medium' },
    ]),
    interactions: JSON.stringify([{ label: 'Caffeine', severity: 'moderate', note: 'Very high caffeine may blunt some effects in some users.' }]),
    sideEffects: JSON.stringify([{ label: 'Water retention', incidence: 'common', mitigation: 'Use steady daily dose; hydrate.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Diuretics', severity: 'moderate', mechanism: 'Hydration balance may be affected.', recommendation: 'Monitor hydration/electrolytes.' }]),
  },
  {
    id: 'sci-d3',
    supplementId: SUPP_IDS.vitD3,
    summary: 'Supports vitamin D status, bone and immune pathways, especially in deficiency.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Deficiency correction', detail: 'Supplementation increases 25(OH)D levels in deficient adults.', citation: 'PMID: 21646368', quality: 'high' },
      { title: 'Respiratory infection risk', detail: 'Meta-analysis suggests modest benefit in some populations.', citation: 'PMID: 28202713', quality: 'medium' },
    ]),
    interactions: JSON.stringify([{ label: 'Vitamin K2', severity: 'synergy', note: 'Commonly paired in bone-health stacks.' }]),
    sideEffects: JSON.stringify([{ label: 'Hypercalcemia at excess dose', incidence: 'rare', mitigation: 'Avoid chronic excessive dosing.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Thiazide diuretics', severity: 'moderate', mechanism: 'May increase calcium-related risk.', recommendation: 'Monitor calcium if high-dose vitamin D used.' }]),
  },
  {
    id: 'sci-omega3',
    supplementId: SUPP_IDS.omega3,
    summary: 'EPA/DHA may support triglycerides and inflammatory markers in select populations.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Triglycerides', detail: 'Higher-dose omega-3 can reduce triglycerides.', citation: 'PMID: 31567003', quality: 'high' },
      { title: 'Cardiovascular signal', detail: 'Outcome data mixed by formulation and cohort.', citation: 'PMID: 30415628', quality: 'medium' },
    ]),
    interactions: JSON.stringify([{ label: 'Vitamin D3', severity: 'synergy', note: 'Common daily stack pairing.' }]),
    sideEffects: JSON.stringify([{ label: 'Fishy burps', incidence: 'common', mitigation: 'Take with meals; use quality products.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Warfarin / anticoagulants', severity: 'high', mechanism: 'Potential additive bleeding effect at higher doses.', recommendation: 'Monitor INR and bleeding risk with clinician.' }]),
  },
  {
    id: 'sci-zinc',
    supplementId: SUPP_IDS.zinc,
    summary: 'Essential trace mineral used for immune function and deficiency correction.',
    sourceCount: 3,
    findings: JSON.stringify([{ title: 'Immune function', detail: 'Adequate zinc supports immune pathways.', citation: 'PMID: 21328251', quality: 'medium' }]),
    interactions: JSON.stringify([{ label: 'Iron', severity: 'moderate', note: 'Compete for absorption at high doses.' }]),
    sideEffects: JSON.stringify([{ label: 'Nausea', incidence: 'common', mitigation: 'Take with food.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Levothyroxine', severity: 'moderate', mechanism: 'Can reduce absorption if co-dosed.', recommendation: 'Separate by 4 hours.' }]),
  },
  {
    id: 'sci-ashwa',
    supplementId: SUPP_IDS.ashwagandha,
    summary: 'Adaptogen with evidence for stress/cortisol support in some populations.',
    sourceCount: 4,
    findings: JSON.stringify([{ title: 'Cortisol reduction', detail: 'Trials suggest reduced stress markers.', citation: 'PMID: 23439798', quality: 'medium' }]),
    interactions: JSON.stringify([{ label: 'Sedatives', severity: 'moderate', note: 'Potential additive calming/sedating effect.' }]),
    sideEffects: JSON.stringify([{ label: 'GI upset', incidence: 'low', mitigation: 'Take with food.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'SSRIs', severity: 'moderate', mechanism: 'Potential additive CNS effects.', recommendation: 'Start low and monitor with clinician if medicated.' }]),
  },
  {
    id: 'sci-ltheanine',
    supplementId: SUPP_IDS.ltheanine,
    summary: 'Commonly used for calm focus; often paired with caffeine.',
    sourceCount: 3,
    findings: JSON.stringify([{ title: 'Attention and calm', detail: 'May improve attention with caffeine while reducing jitters.', citation: 'PMID: 18681988', quality: 'medium' }]),
    interactions: JSON.stringify([{ label: 'Caffeine', severity: 'synergy', note: 'Classic nootropic pairing.' }]),
    sideEffects: JSON.stringify([{ label: 'Drowsiness', incidence: 'low', mitigation: 'Reduce dose in daytime if needed.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Antihypertensives', severity: 'low', mechanism: 'Possible mild additive BP lowering.', recommendation: 'Monitor blood pressure.' }]),
  },
  {
    id: 'sci-coq10',
    supplementId: SUPP_IDS.coq10,
    summary: 'Mitochondrial cofactor commonly used in cardiovascular and statin-support contexts.',
    sourceCount: 3,
    findings: JSON.stringify([{ title: 'Statin myalgia support', detail: 'Some evidence for symptom reduction in statin users.', citation: 'PMID: 29067523', quality: 'medium' }]),
    interactions: JSON.stringify([{ label: 'Statins', severity: 'synergy', note: 'Common adjunct in statin users.' }]),
    sideEffects: JSON.stringify([{ label: 'GI upset', incidence: 'low', mitigation: 'Take with food.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Warfarin', severity: 'moderate', mechanism: 'Potential INR interaction signal.', recommendation: 'Monitor INR if used together.' }]),
  },
  {
    id: 'sci-k2',
    supplementId: SUPP_IDS.vitK2,
    summary: 'Vitamin K2 (MK-7) commonly paired with D3 in bone-health protocols.',
    sourceCount: 3,
    findings: JSON.stringify([{ title: 'Bone/vascular pathways', detail: 'Supports vitamin K-dependent proteins in calcium handling.', citation: 'PMID: 25694037', quality: 'medium' }]),
    interactions: JSON.stringify([{ label: 'Vitamin D3', severity: 'synergy', note: 'Frequently paired for bone-health stacks.' }]),
    sideEffects: JSON.stringify([{ label: 'Generally well tolerated', incidence: 'low', mitigation: 'Use evidence-based dosing.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Warfarin', severity: 'contraindicated', mechanism: 'Vitamin K pathway interaction.', recommendation: 'Avoid unless specifically managed by clinician.' }]),
  },
  {
    id: 'sci-iron',
    supplementId: SUPP_IDS.iron,
    summary: 'Chelated iron form commonly used for deficiency with improved tolerability.',
    sourceCount: 4,
    findings: JSON.stringify([{ title: 'Deficiency correction', detail: 'Raises ferritin/hemoglobin in deficiency contexts.', citation: 'PMID: 25084991', quality: 'high' }]),
    interactions: JSON.stringify([{ label: 'Calcium', severity: 'high', note: 'Significant absorption competition.' }]),
    sideEffects: JSON.stringify([{ label: 'Constipation', incidence: 'common', mitigation: 'Hydration and dose timing.' }]),
    medicineInteractions: JSON.stringify([{ medicineName: 'Levothyroxine', severity: 'high', mechanism: 'Reduces thyroid medication absorption if co-dosed.', recommendation: 'Separate by 4 hours.' }]),
  },
  {
    id: 'sci-vitc',
    supplementId: SUPP_IDS.vitC,
    summary: 'Essential antioxidant vitamin supporting immune function, collagen synthesis, and iron absorption.',
    sourceCount: 5,
    findings: JSON.stringify([
      { title: 'Immune function', detail: 'Supports neutrophil migration and lymphocyte proliferation; may reduce cold duration.', citation: 'PMID: 23440782', quality: 'high' },
      { title: 'Iron absorption', detail: 'Co-ingestion with non-heme iron can significantly increase absorption.', citation: 'PMID: 2507689', quality: 'high' },
      { title: 'Collagen synthesis cofactor', detail: 'Required for hydroxylation of proline and lysine in collagen formation.', citation: 'PMID: 17884994', quality: 'high' },
    ]),
    interactions: JSON.stringify([
      { label: 'Iron', severity: 'synergy', note: 'Vitamin C meaningfully enhances non-heme iron absorption — take together.' },
      { label: 'Zinc', severity: 'low', note: 'Generally safe together; separate if GI sensitivity.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'GI upset / diarrhea at high doses', incidence: 'common', mitigation: 'Use buffered form or split doses if >1g/day.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Warfarin', severity: 'moderate', mechanism: 'High-dose vitamin C (>1g/day) may affect INR.', recommendation: 'Monitor INR if using high-dose supplementation.' },
      { medicineName: 'Chemotherapy agents', severity: 'high', mechanism: 'High-dose vitamin C may interfere with oxidative chemotherapy mechanisms.', recommendation: 'Consult oncologist before supplementing during treatment.' },
    ]),
  },
  {
    id: 'sci-b12',
    supplementId: SUPP_IDS.b12,
    summary: 'Active B12 form supporting nerve health, energy metabolism, and homocysteine regulation.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Nerve function support', detail: 'Methylcobalamin supports myelin sheath maintenance and nerve conduction.', citation: 'PMID: 23356638', quality: 'high' },
      { title: 'Homocysteine reduction', detail: 'B12 combined with folate lowers elevated homocysteine, a cardiovascular risk marker.', citation: 'PMID: 18838531', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'Folate', severity: 'synergy', note: 'B12 and folate work together in the methylation cycle — commonly co-supplemented.' },
      { label: 'Iron', severity: 'low', note: 'Separate by 1+ hours as a general practice.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Generally very well tolerated', incidence: 'low', mitigation: 'Water-soluble; excess excreted.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Metformin', severity: 'high', mechanism: 'Long-term metformin reduces B12 absorption via ileal uptake inhibition.', recommendation: 'Monitor B12 levels annually if on metformin; supplement as needed.' },
      { medicineName: 'Proton pump inhibitors (PPIs)', severity: 'moderate', mechanism: 'Reduces gastric acid needed for B12 release from food proteins.', recommendation: 'Consider supplementing with methylcobalamin if on long-term PPI therapy.' },
    ]),
  },
  {
    id: 'sci-nac',
    supplementId: SUPP_IDS.nac,
    summary: 'Glutathione precursor used for liver support, mucolytic action, and antioxidant defense.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Glutathione replenishment', detail: 'NAC provides cysteine, the rate-limiting precursor to glutathione synthesis.', citation: 'PMID: 25117882', quality: 'high' },
      { title: 'Liver and toxin support', detail: 'Gold-standard treatment for acetaminophen overdose; studied for non-alcoholic fatty liver.', citation: 'PMID: 10594905', quality: 'high' },
    ]),
    interactions: JSON.stringify([
      { label: 'Vitamin C', severity: 'synergy', note: 'Both recycle each other in antioxidant pathways; often stacked.' },
      { label: 'Zinc', severity: 'low', note: 'No significant absorption competition at typical doses.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Nausea / GI upset', incidence: 'low', mitigation: 'Take with a small amount of food.' },
      { label: 'Sulfurous odor (urine/breath)', incidence: 'common', mitigation: 'Expected; not harmful.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Nitroglycerin', severity: 'high', mechanism: 'Additive hypotension; combination studied in angina but increases side effects.', recommendation: 'Avoid combination without physician guidance.' },
      { medicineName: 'Activated charcoal', severity: 'high', mechanism: 'Charcoal adsorbs NAC, reducing efficacy in overdose settings.', recommendation: 'Do not co-administer; used in separate clinical contexts.' },
    ]),
  },
  {
    id: 'sci-berberine',
    supplementId: SUPP_IDS.berberine,
    summary: 'Botanical alkaloid with AMPK activation; evidence for blood glucose, lipids, and insulin sensitivity.',
    sourceCount: 5,
    findings: JSON.stringify([
      { title: 'Blood glucose regulation', detail: 'Meta-analyses show berberine reduces fasting glucose and HbA1c comparably to metformin in T2DM trials.', citation: 'PMID: 18397984', quality: 'high' },
      { title: 'Lipid modulation', detail: 'Reduces LDL cholesterol and triglycerides via PCSK9 inhibition and LDL receptor upregulation.', citation: 'PMID: 20350504', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'CoQ10', severity: 'synergy', note: 'Berberine may reduce mitochondrial function similarly to statins; CoQ10 commonly co-supplemented.' },
      { label: 'Omega-3', severity: 'synergy', note: 'Common metabolic health pairing for lipid and glucose support.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'GI upset / constipation', incidence: 'common', mitigation: 'Take with meals; start at 500 mg/day and titrate.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Metformin', severity: 'high', mechanism: 'Additive blood glucose lowering; risk of hypoglycemia when combined.', recommendation: 'Monitor blood glucose closely; dosage adjustment may be needed.' },
      { medicineName: 'Cyclosporine', severity: 'high', mechanism: 'Berberine inhibits CYP3A4, increasing cyclosporine levels.', recommendation: 'Avoid combination or monitor drug levels under physician supervision.' },
      { medicineName: 'Statins', severity: 'moderate', mechanism: 'CYP3A4 inhibition may increase statin plasma levels.', recommendation: 'Monitor for statin side effects; inform prescriber.' },
    ]),
  },
  {
    id: 'sci-lionsmane',
    supplementId: SUPP_IDS.lionsMane,
    summary: 'Medicinal mushroom with NGF-stimulating compounds (hericenones/erinacines) supporting cognitive and nerve health.',
    sourceCount: 3,
    findings: JSON.stringify([
      { title: 'Cognitive function', detail: 'RCT in mild cognitive impairment showed improved cognitive scores with 250 mg 3x/day over 16 weeks.', citation: 'PMID: 19001767', quality: 'medium' },
      { title: 'Nerve growth factor stimulation', detail: 'Erinacines cross the blood-brain barrier and stimulate NGF synthesis in preclinical models.', citation: 'PMID: 18844328', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'Rhodiola', severity: 'synergy', note: 'Common cognitive performance stack.' },
      { label: 'Omega-3', severity: 'synergy', note: 'Omega-3 DHA supports neuronal membrane health alongside NGF support.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'GI discomfort (rare)', incidence: 'low', mitigation: 'Take with food; use fruiting body or dual-extract products.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Anticoagulants', severity: 'moderate', mechanism: 'Theoretical platelet aggregation effects observed in animal studies.', recommendation: 'Monitor bleeding risk; inform prescriber.' },
      { medicineName: 'Diabetes medications', severity: 'low', mechanism: 'Modest glucose-lowering effects may add to medication effect.', recommendation: 'Monitor blood glucose when starting.' },
    ]),
  },
  {
    id: 'sci-melatonin',
    supplementId: SUPP_IDS.melatonin,
    summary: 'Endogenous sleep hormone; supplementation shortens sleep onset latency and supports circadian rhythm regulation.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Sleep onset latency', detail: 'Meta-analyses confirm melatonin reduces time to fall asleep; effect strongest in circadian-disrupted populations.', citation: 'PMID: 22552138', quality: 'high' },
      { title: 'Jet lag mitigation', detail: 'Timed melatonin (destination bedtime) reduces jet lag severity in controlled trials.', citation: 'PMID: 12174486', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'Ashwagandha', severity: 'synergy', note: 'Both support sleep; common nighttime stack at standard doses.' },
      { label: 'Magnesium', severity: 'synergy', note: 'Classic sleep protocol triple: Melatonin + Magnesium + Ashwagandha.' },
      { label: 'L-Theanine', severity: 'synergy', note: 'Additive calming effect; well-tolerated combination.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Morning grogginess', incidence: 'common', mitigation: 'Use lowest effective dose (0.5 mg); avoid high-dose supplementation.' },
      { label: 'Vivid dreams', incidence: 'common', mitigation: 'Reduce dose or take earlier in the evening.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Benzodiazepines / sedatives', severity: 'moderate', mechanism: 'Additive CNS sedation.', recommendation: 'Use lowest effective melatonin dose; monitor for excessive sedation.' },
      { medicineName: 'Fluvoxamine (SSRI)', severity: 'high', mechanism: 'Fluvoxamine inhibits CYP1A2, dramatically increasing melatonin plasma levels.', recommendation: 'Avoid or use very low dose melatonin under physician guidance.' },
      { medicineName: 'Anticoagulants', severity: 'low', mechanism: 'Theoretical antiplatelet activity at high doses.', recommendation: 'Use standard low doses (0.5–3 mg); monitor if on anticoagulant therapy.' },
    ]),
  },
  {
    id: 'sci-rhodiola',
    supplementId: SUPP_IDS.rhodiola,
    summary: 'Adaptogen with evidence for physical and mental fatigue resistance via HPA axis modulation.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Fatigue and stress resilience', detail: 'Repeated-measure RCTs show reduced fatigue and improved attention under stress with 200–400 mg/day.', citation: 'PMID: 19016404', quality: 'medium' },
      { title: 'Endurance performance', detail: 'Some trials show improved VO2 max proxies and time-to-exhaustion with acute dosing.', citation: 'PMID: 14983953', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'Ashwagandha', severity: 'synergy', note: 'Classic adaptogen stack for stress and performance.' },
      { label: "Lion's Mane", severity: 'synergy', note: 'Common cognitive and focus protocol pairing.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Insomnia / restlessness if taken late', incidence: 'common', mitigation: 'Take only in the morning on an empty stomach.' },
      { label: 'Mild dizziness (initial doses)', incidence: 'low', mitigation: 'Start at 100 mg/day and titrate.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'SSRIs / SNRIs', severity: 'moderate', mechanism: 'Theoretical serotonin pathway interaction at high doses.', recommendation: 'Start low and monitor mood/symptoms; inform prescriber.' },
      { medicineName: 'MAO inhibitors (MAOIs)', severity: 'contraindicated', mechanism: 'Potential serotonin syndrome risk.', recommendation: 'Do not combine with MAOIs.' },
      { medicineName: 'CYP3A4 substrates', severity: 'moderate', mechanism: 'Rhodiola may moderately inhibit CYP3A4, altering drug metabolism.', recommendation: 'Use caution with narrow-therapeutic-index CYP3A4 drugs.' },
    ]),
  },
  {
    id: 'sci-collagen',
    supplementId: SUPP_IDS.collagen,
    summary: 'Hydrolyzed collagen peptides support skin elasticity, joint cartilage, and connective tissue health.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Skin elasticity and hydration', detail: 'Oral collagen peptides (2.5–10 g/day) improved skin elasticity and hydration in controlled trials.', citation: 'PMID: 24401291', quality: 'medium' },
      { title: 'Joint and cartilage support', detail: 'Collagen hydrolysate (10 g/day) reduced joint pain scores in athletes and OA patients.', citation: 'PMID: 18416885', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: 'Vitamin C', severity: 'synergy', note: 'Vitamin C is an essential cofactor for collagen synthesis — always pair together.' },
      { label: 'Omega-3', severity: 'synergy', note: 'Omega-3 anti-inflammatory effects complement collagen joint support.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Generally very well tolerated', incidence: 'low', mitigation: 'Use high-quality sourced product; disclose to clinician if fish-allergic (marine collagen).' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'No clinically significant interactions identified', severity: 'low', mechanism: 'Collagen peptides are digested as amino acids with minimal pharmacological activity.', recommendation: 'Standard dosing is safe alongside most medications.' },
    ]),
  },
  {
    id: 'sci-boron',
    supplementId: SUPP_IDS.boron,
    summary: 'Trace mineral supporting bone health, hormonal balance, and anti-inflammatory pathways.',
    sourceCount: 3,
    findings: JSON.stringify([
      { title: 'Bone and mineral metabolism', detail: 'Boron (3 mg/day) may improve calcium retention and bone density in postmenopausal women.', citation: 'PMID: 8892217', quality: 'medium' },
      { title: 'Testosterone and joint health', detail: 'Limited evidence suggests boron may modestly support free testosterone and reduce joint inflammation markers.', citation: 'PMID: 9696721', quality: 'low' },
    ]),
    interactions: JSON.stringify([
      { label: 'Calcium / Magnesium', severity: 'synergy', note: 'Boron enhances mineral retention — often stacked in bone-health protocols.' },
      { label: 'Vitamin D3', severity: 'synergy', note: 'Commonly co-supplemented in bone support protocols.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'Generally well tolerated', incidence: 'low', mitigation: 'Keep supplementation to 3 mg/day or less; excess may cause toxicity.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'No major interactions identified', severity: 'low', mechanism: 'Boron is a trace mineral with minimal pharmacological interaction potential.', recommendation: 'Safe for use alongside most medications at standard dosing.' },
    ]),
  },
  {
    id: 'sci-turkeyTail',
    supplementId: SUPP_IDS.turkeyTail,
    summary: 'Medicinal polypore mushroom rich in beta-glucans; supports immune function and gut health.',
    sourceCount: 4,
    findings: JSON.stringify([
      { title: 'Immune modulation', detail: 'Beta-glucan and polysaccharide content stimulates NK cell and macrophage activity.', citation: 'PMID: 12403227', quality: 'medium' },
      { title: 'Gut microbiota support', detail: 'Turkey tail acts as prebiotic, promoting beneficial bacteria growth and SCFA production.', citation: 'PMID: 23107147', quality: 'medium' },
      { title: 'Adjunctive oncology research', detail: 'Lentinan and PSK (polysaccharide K extract) studied as adjuncts in cancer therapy; improving some outcome markers in trials.', citation: 'PMID: 17316240', quality: 'medium' },
    ]),
    interactions: JSON.stringify([
      { label: "Lion's Mane", severity: 'synergy', note: 'Both are medicinal mushrooms; often stacked for immune + cognitive support.' },
      { label: 'Rhodiola / Ashwagandha', severity: 'synergy', note: 'Complementary to adaptogenic stacking for immune resilience.' },
    ]),
    sideEffects: JSON.stringify([
      { label: 'GI effects (mild)', incidence: 'low', mitigation: 'May cause loose stools initially as microbiota adjusts; take with food.' },
    ]),
    medicineInteractions: JSON.stringify([
      { medicineName: 'Immunosuppressants', severity: 'moderate', mechanism: 'Turkey tail stimulates immune function, potentially counteracting immunosuppressive therapy.', recommendation: 'Consult with physician before use if on post-transplant or autoimmune-suppressing medications.' },
      { medicineName: 'Anticoagulants / Antiplatelets', severity: 'low', mechanism: 'Theoretical antiplatelet activity in some compounds; modest effect likely.', recommendation: 'Monitor bleeding risk; inform prescriber.' },
    ]),
  },
];

export const socialData = supplementsData.map((s, i) => ({
  id: `soc-${i + 1}`,
  supplementId: s.id,
  transcriptSummary: `${s.name} is discussed across research-focused channels for its role in supporting physiological function. See the Evidence section for peer-reviewed studies.`,
  anecdotes: JSON.stringify([
    { quote: `${s.name} was one of the most discussed additions to my protocol.`, source: 'YouTube Transcript', reliability: 'medium', stance: 'pro' },
  ]),
}));

export const sentimentData = supplementsData.map((s, i) => ({
  id: `sent-${i + 1}`,
  supplementId: s.id,
  positive: 0.72,
  neutral: 0.18,
  negative: 0.10,
  topPositive: `${s.name} helped consistency`,
  topNegative: 'Price or tolerance variability',
}));

export const dosageData = [
  { id: 'dose-mag', supplementId: SUPP_IDS.magnesium, loading: null, maintenance: '200-400 mg/day', formula: 'start low, titrate', unit: 'mg', perKgFactor: null },
  { id: 'dose-creatine', supplementId: SUPP_IDS.creatine, loading: 'Optional 20 g/day split x5 days', maintenance: '3-5 g/day', formula: 'weightKg * 0.03 g', unit: 'g', perKgFactor: 0.03 },
  { id: 'dose-d3', supplementId: SUPP_IDS.vitD3, loading: null, maintenance: '1000-5000 IU/day based on labs', formula: 'lab guided', unit: 'IU', perKgFactor: null },
  { id: 'dose-omega3', supplementId: SUPP_IDS.omega3, loading: null, maintenance: '1-2 g EPA+DHA/day', formula: 'goal dependent', unit: 'g', perKgFactor: null },
  { id: 'dose-zinc', supplementId: SUPP_IDS.zinc, loading: null, maintenance: '10-30 mg/day', formula: 'avoid chronic excess', unit: 'mg', perKgFactor: null },
  { id: 'dose-ashwa', supplementId: SUPP_IDS.ashwagandha, loading: null, maintenance: '300-600 mg/day', formula: 'split if needed', unit: 'mg', perKgFactor: null },
  { id: 'dose-ltheanine', supplementId: SUPP_IDS.ltheanine, loading: null, maintenance: '100-200 mg per dose', formula: 'as needed', unit: 'mg', perKgFactor: null },
  { id: 'dose-coq10', supplementId: SUPP_IDS.coq10, loading: null, maintenance: '100-200 mg/day', formula: 'with meals', unit: 'mg', perKgFactor: null },
  { id: 'dose-k2', supplementId: SUPP_IDS.vitK2, loading: null, maintenance: '90-180 mcg/day', formula: 'daily', unit: 'mcg', perKgFactor: null },
  { id: 'dose-iron', supplementId: SUPP_IDS.iron, loading: null, maintenance: '18-27 mg/day as indicated', formula: 'lab guided', unit: 'mg', perKgFactor: null },
  { id: 'dose-vitc', supplementId: SUPP_IDS.vitC, loading: null, maintenance: '250-1000 mg/day', formula: 'start 250 mg, titrate to tolerance', unit: 'mg', perKgFactor: null },
  { id: 'dose-b12', supplementId: SUPP_IDS.b12, loading: null, maintenance: '500-1000 mcg/day', formula: 'oral or sublingual; lab guided if deficient', unit: 'mcg', perKgFactor: null },
  { id: 'dose-nac', supplementId: SUPP_IDS.nac, loading: null, maintenance: '600-1800 mg/day in divided doses', formula: 'split morning and evening', unit: 'mg', perKgFactor: null },
  { id: 'dose-berberine', supplementId: SUPP_IDS.berberine, loading: null, maintenance: '1000-1500 mg/day (500 mg 2-3x with meals)', formula: 'split dosing with meals required', unit: 'mg', perKgFactor: null },
  { id: 'dose-lionsmane', supplementId: SUPP_IDS.lionsMane, loading: null, maintenance: '500-1000 mg/day (fruiting body extract)', formula: 'look for >25% beta-glucans', unit: 'mg', perKgFactor: null },
  { id: 'dose-melatonin', supplementId: SUPP_IDS.melatonin, loading: null, maintenance: '0.5-5 mg, 30-60 min before bed', formula: 'start at lowest effective dose (0.5 mg)', unit: 'mg', perKgFactor: null },
  { id: 'dose-rhodiola', supplementId: SUPP_IDS.rhodiola, loading: null, maintenance: '200-600 mg/day standardized extract', formula: '3% rosavins / 1% salidroside standard', unit: 'mg', perKgFactor: null },
  { id: 'dose-collagen', supplementId: SUPP_IDS.collagen, loading: null, maintenance: '10-20 g/day', formula: 'powder form; mix into beverage', unit: 'g', perKgFactor: null },
  { id: 'dose-boron', supplementId: SUPP_IDS.boron, loading: null, maintenance: '1-3 mg/day', formula: 'do not exceed 3 mg/day chronically', unit: 'mg', perKgFactor: null },
  { id: 'dose-turkeyTail', supplementId: SUPP_IDS.turkeyTail, loading: null, maintenance: '1000-2000 mg/day (fruiting body or extract)', formula: 'look for >30% polysaccharide content', unit: 'mg', perKgFactor: null },
];

export const scheduleRulesData = [
  { id: 'rule-mag', supplementId: SUPP_IDS.magnesium, preferredTime: 'bedtime', withFood: true, foodType: 'light meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: true },
  { id: 'rule-creatine', supplementId: SUPP_IDS.creatine, preferredTime: 'morning', withFood: false, foodType: null, emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-d3', supplementId: SUPP_IDS.vitD3, preferredTime: 'morning', withFood: true, foodType: 'fat-containing meal', emptyStomach: false, fatSoluble: true, stimulant: false, sedating: false },
  { id: 'rule-omega3', supplementId: SUPP_IDS.omega3, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: true, stimulant: false, sedating: false },
  { id: 'rule-zinc', supplementId: SUPP_IDS.zinc, preferredTime: 'afternoon', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-ashwa', supplementId: SUPP_IDS.ashwagandha, preferredTime: 'evening', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: true },
  { id: 'rule-ltheanine', supplementId: SUPP_IDS.ltheanine, preferredTime: 'evening', withFood: false, foodType: null, emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-coq10', supplementId: SUPP_IDS.coq10, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: true, stimulant: false, sedating: false },
  { id: 'rule-k2', supplementId: SUPP_IDS.vitK2, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: true, stimulant: false, sedating: false },
  { id: 'rule-iron', supplementId: SUPP_IDS.iron, preferredTime: 'morning', withFood: false, foodType: null, emptyStomach: true, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-vitc', supplementId: SUPP_IDS.vitC, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-b12', supplementId: SUPP_IDS.b12, preferredTime: 'morning', withFood: false, foodType: null, emptyStomach: true, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-nac', supplementId: SUPP_IDS.nac, preferredTime: 'morning', withFood: false, foodType: null, emptyStomach: true, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-berberine', supplementId: SUPP_IDS.berberine, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-lionsmane', supplementId: SUPP_IDS.lionsMane, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-melatonin', supplementId: SUPP_IDS.melatonin, preferredTime: 'bedtime', withFood: false, foodType: null, emptyStomach: false, fatSoluble: false, stimulant: false, sedating: true },
  { id: 'rule-rhodiola', supplementId: SUPP_IDS.rhodiola, preferredTime: 'morning', withFood: false, foodType: null, emptyStomach: true, fatSoluble: false, stimulant: true, sedating: false },
  { id: 'rule-collagen', supplementId: SUPP_IDS.collagen, preferredTime: 'morning', withFood: true, foodType: 'any beverage', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-boron', supplementId: SUPP_IDS.boron, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
  { id: 'rule-turkeyTail', supplementId: SUPP_IDS.turkeyTail, preferredTime: 'morning', withFood: true, foodType: 'meal', emptyStomach: false, fatSoluble: false, stimulant: false, sedating: false },
];

export const conflictsData = [
  { id: 'conf-iron-mag', supplementAId: SUPP_IDS.iron, supplementBId: SUPP_IDS.magnesium, conflictType: 'spacing_required', minSpacingHours: 2, mechanism: 'Mineral absorption competition.', severity: 'high' },
  { id: 'conf-iron-zinc', supplementAId: SUPP_IDS.iron, supplementBId: SUPP_IDS.zinc, conflictType: 'spacing_required', minSpacingHours: 2, mechanism: 'Mineral transporter competition.', severity: 'moderate' },
  { id: 'conf-d3-k2', supplementAId: SUPP_IDS.vitD3, supplementBId: SUPP_IDS.vitK2, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Common bone-health synergy.', severity: 'low' },
  { id: 'conf-vitc-iron', supplementAId: SUPP_IDS.vitC, supplementBId: SUPP_IDS.iron, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Vitamin C enhances non-heme iron absorption significantly.', severity: 'low' },
  { id: 'conf-collagen-vitc', supplementAId: SUPP_IDS.collagen, supplementBId: SUPP_IDS.vitC, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Vitamin C is a cofactor for collagen hydroxylation — optimal to co-administer.', severity: 'low' },
  { id: 'conf-melatonin-ashwa', supplementAId: SUPP_IDS.melatonin, supplementBId: SUPP_IDS.ashwagandha, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Both support sleep; additive calming effect at standard doses.', severity: 'low' },
  { id: 'conf-rhodiola-ashwa', supplementAId: SUPP_IDS.rhodiola, supplementBId: SUPP_IDS.ashwagandha, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Classic adaptogen pairing for stress resilience and HPA axis support.', severity: 'low' },
  { id: 'conf-boron-vitd', supplementAId: SUPP_IDS.boron, supplementBId: SUPP_IDS.vitD3, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Boron enhances mineral retention; common in bone-health stacks with vitamin D.', severity: 'low' },
  { id: 'conf-turkeyTail-lionsMane', supplementAId: SUPP_IDS.turkeyTail, supplementBId: SUPP_IDS.lionsMane, conflictType: 'synergistic', minSpacingHours: null, mechanism: 'Both medicinal mushrooms; dual immune + cognitive support stack.', severity: 'low' },
];

export const medicineInteractionsData = [
  { id: 'mi-mag-abx', supplementId: SUPP_IDS.magnesium, medicineName: 'Tetracycline antibiotics', medicineClass: 'antibiotic', severity: 'high', mechanism: 'Chelation reduces absorption.', recommendation: 'Separate by 2-4 hours.', source: 'PMID: 14596323' },
  { id: 'mi-creatine-diur', supplementId: SUPP_IDS.creatine, medicineName: 'Diuretics', medicineClass: 'diuretic', severity: 'moderate', mechanism: 'Hydration/electrolyte dynamics.', recommendation: 'Monitor hydration and electrolytes.', source: null },
  { id: 'mi-d3-thiazide', supplementId: SUPP_IDS.vitD3, medicineName: 'Thiazide diuretics', medicineClass: 'diuretic', severity: 'moderate', mechanism: 'May increase calcium-related risk.', recommendation: 'Monitor calcium under clinician care.', source: 'PMID: 21646368' },
  { id: 'mi-omega3-warfarin', supplementId: SUPP_IDS.omega3, medicineName: 'Warfarin', medicineClass: 'blood_thinner', severity: 'high', mechanism: 'Potential additive bleeding effect.', recommendation: 'Monitor INR with clinician.', source: 'PMID: 30415628' },
  { id: 'mi-zinc-thyroid', supplementId: SUPP_IDS.zinc, medicineName: 'Levothyroxine', medicineClass: 'thyroid', severity: 'moderate', mechanism: 'Can reduce absorption.', recommendation: 'Separate by 4 hours.', source: null },
  { id: 'mi-ashwa-ssri', supplementId: SUPP_IDS.ashwagandha, medicineName: 'SSRIs', medicineClass: 'antidepressant', severity: 'moderate', mechanism: 'Potential additive CNS effects.', recommendation: 'Start low and monitor symptoms.', source: 'PMID: 19718255' },
  { id: 'mi-ltheanine-bp', supplementId: SUPP_IDS.ltheanine, medicineName: 'Antihypertensives', medicineClass: 'blood_pressure', severity: 'low', mechanism: 'Possible mild additive BP lowering.', recommendation: 'Monitor blood pressure.', source: null },
  { id: 'mi-coq10-warfarin', supplementId: SUPP_IDS.coq10, medicineName: 'Warfarin', medicineClass: 'blood_thinner', severity: 'moderate', mechanism: 'Potential INR interaction signal.', recommendation: 'Monitor INR when starting/stopping.', source: null },
  { id: 'mi-k2-warfarin', supplementId: SUPP_IDS.vitK2, medicineName: 'Warfarin', medicineClass: 'blood_thinner', severity: 'contraindicated', mechanism: 'Vitamin K pathway interaction.', recommendation: 'Avoid unless managed by clinician.', source: null },
  { id: 'mi-iron-thyroid', supplementId: SUPP_IDS.iron, medicineName: 'Levothyroxine', medicineClass: 'thyroid', severity: 'high', mechanism: 'Reduces absorption if co-dosed.', recommendation: 'Separate by 4 hours.', source: 'PMID: 25084991' },
  { id: 'mi-vitc-warfarin', supplementId: SUPP_IDS.vitC, medicineName: 'Warfarin', medicineClass: 'blood_thinner', severity: 'moderate', mechanism: 'High-dose vitamin C (>1g/day) may affect INR unpredictably.', recommendation: 'Monitor INR; inform prescriber if taking high-dose vitamin C.', source: null },
  { id: 'mi-vitc-chemo', supplementId: SUPP_IDS.vitC, medicineName: 'Chemotherapy agents', medicineClass: 'oncology', severity: 'high', mechanism: 'High-dose antioxidant may interfere with pro-oxidant chemotherapy mechanisms.', recommendation: 'Consult oncologist before supplementing during active cancer treatment.', source: null },
  { id: 'mi-b12-metformin', supplementId: SUPP_IDS.b12, medicineName: 'Metformin', medicineClass: 'antidiabetic', severity: 'high', mechanism: 'Metformin inhibits ileal B12 absorption via calcium-dependent mechanism.', recommendation: 'Monitor B12 levels annually; supplement methylcobalamin as indicated.', source: 'PMID: 21244186' },
  { id: 'mi-b12-ppi', supplementId: SUPP_IDS.b12, medicineName: 'Proton pump inhibitors', medicineClass: 'antacid', severity: 'moderate', mechanism: 'Reduced gastric acid impairs B12 release from food proteins.', recommendation: 'Consider B12 supplementation on long-term PPI therapy.', source: null },
  { id: 'mi-nac-nitro', supplementId: SUPP_IDS.nac, medicineName: 'Nitroglycerin', medicineClass: 'vasodilator', severity: 'high', mechanism: 'Additive hypotensive effect; combination increases headache and hypotension risk.', recommendation: 'Avoid co-use outside clinical supervision.', source: null },
  { id: 'mi-berberine-metformin', supplementId: SUPP_IDS.berberine, medicineName: 'Metformin', medicineClass: 'antidiabetic', severity: 'high', mechanism: 'Additive blood glucose lowering — hypoglycemia risk.', recommendation: 'Monitor blood glucose closely; dosage adjustment may be required.', source: 'PMID: 18397984' },
  { id: 'mi-berberine-statins', supplementId: SUPP_IDS.berberine, medicineName: 'Statins', medicineClass: 'statin', severity: 'moderate', mechanism: 'CYP3A4 inhibition may increase statin plasma concentrations.', recommendation: 'Monitor for statin-related side effects; inform prescriber.', source: null },
  { id: 'mi-lionsmane-anticoag', supplementId: SUPP_IDS.lionsMane, medicineName: 'Anticoagulants', medicineClass: 'blood_thinner', severity: 'moderate', mechanism: 'Theoretical platelet effects observed in animal studies.', recommendation: 'Monitor bleeding risk; disclose use to prescriber.', source: null },
  { id: 'mi-melatonin-benzos', supplementId: SUPP_IDS.melatonin, medicineName: 'Benzodiazepines / sedatives', medicineClass: 'sedative', severity: 'moderate', mechanism: 'Additive CNS sedation.', recommendation: 'Use lowest effective melatonin dose; monitor for excessive sedation.', source: null },
  { id: 'mi-melatonin-fluvox', supplementId: SUPP_IDS.melatonin, medicineName: 'Fluvoxamine', medicineClass: 'antidepressant', severity: 'high', mechanism: 'CYP1A2 inhibition by fluvoxamine dramatically increases melatonin plasma levels.', recommendation: 'Avoid or use trace dose (0.1-0.3 mg) under physician guidance.', source: null },
  { id: 'mi-rhodiola-ssri', supplementId: SUPP_IDS.rhodiola, medicineName: 'SSRIs / SNRIs', medicineClass: 'antidepressant', severity: 'moderate', mechanism: 'Theoretical serotonergic interaction; risk increases at high rhodiola doses.', recommendation: 'Start at low dose and monitor for serotonin-related symptoms.', source: null },
  { id: 'mi-rhodiola-maoi', supplementId: SUPP_IDS.rhodiola, medicineName: 'MAO inhibitors (MAOIs)', medicineClass: 'antidepressant', severity: 'contraindicated', mechanism: 'Potential serotonin syndrome risk.', recommendation: 'Do not combine with MAOIs.', source: null },
  { id: 'mi-collagen-general', supplementId: SUPP_IDS.collagen, medicineName: 'No clinically significant interactions identified', medicineClass: null, severity: 'low', mechanism: 'Collagen peptides are digested as amino acids with minimal pharmacological activity.', recommendation: 'Standard dosing is safe alongside most medications. Disclose to clinician if using fish-sourced collagen with known fish allergy.', source: null },
  { id: 'mi-boron-general', supplementId: SUPP_IDS.boron, medicineName: 'No major interactions identified', medicineClass: null, severity: 'low', mechanism: 'Boron is a trace mineral with minimal pharmacological interaction potential at standard dosing.', recommendation: 'Safe for use alongside most medications. Avoid excess (>3 mg/day) due to toxicity risk.', source: null },
  { id: 'mi-turkeyTail-immunosuppressants', supplementId: SUPP_IDS.turkeyTail, medicineName: 'Immunosuppressants', medicineClass: 'immunosuppressant', severity: 'moderate', mechanism: 'Turkey tail stimulates immune function, potentially counteracting immunosuppressive therapy in transplant or autoimmune contexts.', recommendation: 'Consult physician before use if on immunosuppressive medications.', source: null },
  { id: 'mi-turkeyTail-anticoag', supplementId: SUPP_IDS.turkeyTail, medicineName: 'Anticoagulants / Antiplatelets', medicineClass: 'blood_thinner', severity: 'low', mechanism: 'Theoretical antiplatelet activity in some beta-glucan compounds; modest effect at standard dosing.', recommendation: 'Monitor bleeding risk; inform prescriber of turkey tail use.', source: null },
];

export const affiliateData = [
  { id: 'aff-mag', supplementId: SUPP_IDS.magnesium, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Magnesium Glycinate', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$12.99', productForm: 'capsule', trustScore: 8, priorityScore: 90, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-creatine', supplementId: SUPP_IDS.creatine, partnerName: 'Thorne', partnerType: 'brand_direct', productName: 'Creatine Monohydrate', destinationUrl: 'https://www.thorne.com/', affiliateUrl: 'https://www.thorne.com/?ref=protocolsai', priceDisplay: '$38.00', productForm: 'powder', trustScore: 9, priorityScore: 95, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-d3', supplementId: SUPP_IDS.vitD3, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Vitamin D3', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$14.49', productForm: 'capsule', trustScore: 8, priorityScore: 85, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-omega3', supplementId: SUPP_IDS.omega3, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Omega-3 Fish Oil', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$27.99', productForm: 'capsule', trustScore: 9, priorityScore: 90, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-zinc', supplementId: SUPP_IDS.zinc, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Zinc Picolinate', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$13.00', productForm: 'capsule', trustScore: 8, priorityScore: 84, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-ashwa', supplementId: SUPP_IDS.ashwagandha, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Ashwagandha KSM-66', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$14.99', productForm: 'capsule', trustScore: 8, priorityScore: 83, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-ltheanine', supplementId: SUPP_IDS.ltheanine, partnerName: 'Amazon', partnerType: 'retailer', productName: 'L-Theanine', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$15.99', productForm: 'capsule', trustScore: 8, priorityScore: 82, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-coq10', supplementId: SUPP_IDS.coq10, partnerName: 'Amazon', partnerType: 'retailer', productName: 'CoQ10 Ubiquinol', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$22.99', productForm: 'capsule', trustScore: 8, priorityScore: 81, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-k2', supplementId: SUPP_IDS.vitK2, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Vitamin K2 MK-7', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$12.49', productForm: 'capsule', trustScore: 8, priorityScore: 80, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-iron', supplementId: SUPP_IDS.iron, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Iron Bisglycinate', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$11.49', productForm: 'capsule', trustScore: 8, priorityScore: 79, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-vitc', supplementId: SUPP_IDS.vitC, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Vitamin C 1000mg', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$10.99', productForm: 'capsule', trustScore: 8, priorityScore: 78, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-b12', supplementId: SUPP_IDS.b12, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Methylcobalamin B12', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$11.99', productForm: 'capsule', trustScore: 8, priorityScore: 77, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-nac', supplementId: SUPP_IDS.nac, partnerName: 'Amazon', partnerType: 'retailer', productName: 'NAC 600mg', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$14.99', productForm: 'capsule', trustScore: 8, priorityScore: 76, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-berberine', supplementId: SUPP_IDS.berberine, partnerName: 'Thorne', partnerType: 'brand_direct', productName: 'Berberine-500', destinationUrl: 'https://www.thorne.com/', affiliateUrl: 'https://www.thorne.com/?ref=protocolsai', priceDisplay: '$36.00', productForm: 'capsule', trustScore: 9, priorityScore: 88, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-lionsmane', supplementId: SUPP_IDS.lionsMane, partnerName: 'Amazon', partnerType: 'retailer', productName: "Lion's Mane Extract", destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$19.99', productForm: 'capsule', trustScore: 8, priorityScore: 75, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-melatonin', supplementId: SUPP_IDS.melatonin, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Melatonin 0.5mg', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$7.99', productForm: 'capsule', trustScore: 8, priorityScore: 74, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-rhodiola', supplementId: SUPP_IDS.rhodiola, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Rhodiola Rosea Extract', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$16.99', productForm: 'capsule', trustScore: 8, priorityScore: 73, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-collagen', supplementId: SUPP_IDS.collagen, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Collagen Peptides Powder', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$24.99', productForm: 'powder', trustScore: 8, priorityScore: 72, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-boron', supplementId: SUPP_IDS.boron, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Boron 3mg', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$8.99', productForm: 'capsule', trustScore: 8, priorityScore: 70, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
  { id: 'aff-turkeyTail', supplementId: SUPP_IDS.turkeyTail, partnerName: 'Amazon', partnerType: 'retailer', productName: 'Turkey Tail Extract 1000mg', destinationUrl: 'https://www.amazon.com/', affiliateUrl: 'https://www.amazon.com/?tag=protocolsai-20', priceDisplay: '$21.99', productForm: 'capsule', trustScore: 8, priorityScore: 71, isPrimary: true, isActive: true, complianceStatus: 'approved', countryCode: 'US', lastVerifiedAt: now },
];

export const companionData = [
  { id: 'cmp-d3-k2', supplementId: SUPP_IDS.vitD3, companionSupplementId: SUPP_IDS.vitK2, why: 'K2 helps direct calcium to bone when using Vitamin D3.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-d3-omega3', supplementId: SUPP_IDS.vitD3, companionSupplementId: SUPP_IDS.omega3, why: 'Fat-soluble pairing commonly used in daily stacks.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-d3-mag', supplementId: SUPP_IDS.vitD3, companionSupplementId: SUPP_IDS.magnesium, why: 'Magnesium supports vitamin D metabolism.', strength: 'common', sortOrder: 3 },
  { id: 'cmp-mag-ltheanine', supplementId: SUPP_IDS.magnesium, companionSupplementId: SUPP_IDS.ltheanine, why: 'Common nighttime calm/sleep pairing.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-ltheanine-mag', supplementId: SUPP_IDS.ltheanine, companionSupplementId: SUPP_IDS.magnesium, why: 'Common nighttime calm/sleep pairing with magnesium.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-ltheanine-melatonin', supplementId: SUPP_IDS.ltheanine, companionSupplementId: SUPP_IDS.melatonin, why: 'Often paired for sleep onset and reduced bedtime anxiety.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-creatine-omega3', supplementId: SUPP_IDS.creatine, companionSupplementId: SUPP_IDS.omega3, why: 'Often stacked for performance + recovery.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-zinc-mag', supplementId: SUPP_IDS.zinc, companionSupplementId: SUPP_IDS.magnesium, why: 'Common mineral stack (with spacing awareness).', strength: 'common', sortOrder: 1 },
  { id: 'cmp-ashwa-mag', supplementId: SUPP_IDS.ashwagandha, companionSupplementId: SUPP_IDS.magnesium, why: 'Common stress/sleep support stack.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-coq10-omega3', supplementId: SUPP_IDS.coq10, companionSupplementId: SUPP_IDS.omega3, why: 'Often paired for cardiovascular support.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-k2-d3', supplementId: SUPP_IDS.vitK2, companionSupplementId: SUPP_IDS.vitD3, why: 'K2 is commonly paired with vitamin D3 in bone-health protocols.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-k2-mag', supplementId: SUPP_IDS.vitK2, companionSupplementId: SUPP_IDS.magnesium, why: 'Magnesium supports vitamin D and bone-health pathways often stacked with K2.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-iron-vitc', supplementId: SUPP_IDS.iron, companionSupplementId: SUPP_IDS.vitC, why: 'Vitamin C significantly improves non-heme iron absorption and is commonly taken with iron.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-iron-b12', supplementId: SUPP_IDS.iron, companionSupplementId: SUPP_IDS.b12, why: 'Iron and B12 are commonly paired in deficiency-repletion protocols.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-omega3-d3', supplementId: SUPP_IDS.omega3, companionSupplementId: SUPP_IDS.vitD3, why: 'Common daily fat-soluble stack pairing for cardiovascular and general wellness support.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-omega3-coq10', supplementId: SUPP_IDS.omega3, companionSupplementId: SUPP_IDS.coq10, why: 'Often paired for cardiovascular support and mitochondrial energy support.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-vitc-iron', supplementId: SUPP_IDS.vitC, companionSupplementId: SUPP_IDS.iron, why: 'Vitamin C significantly enhances non-heme iron absorption — always take together.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-vitc-collagen', supplementId: SUPP_IDS.vitC, companionSupplementId: SUPP_IDS.collagen, why: 'Vitamin C is a required cofactor for collagen synthesis; pair for maximum effect.', strength: 'strong', sortOrder: 2 },
  { id: 'cmp-b12-mag', supplementId: SUPP_IDS.b12, companionSupplementId: SUPP_IDS.magnesium, why: 'B12 and magnesium are commonly co-deficient; useful together for energy and mood.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-b12-omega3', supplementId: SUPP_IDS.b12, companionSupplementId: SUPP_IDS.omega3, why: 'Combined brain health stack for cognitive and mood support.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-nac-vitc', supplementId: SUPP_IDS.nac, companionSupplementId: SUPP_IDS.vitC, why: 'NAC and vitamin C recycle each other in antioxidant pathways; synergistic stack.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-berberine-coq10', supplementId: SUPP_IDS.berberine, companionSupplementId: SUPP_IDS.coq10, why: 'Berberine may reduce CoQ10 levels like statins; CoQ10 commonly co-supplemented.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-berberine-omega3', supplementId: SUPP_IDS.berberine, companionSupplementId: SUPP_IDS.omega3, why: 'Common metabolic health stack for lipid and glucose support.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-lionsmane-rhodiola', supplementId: SUPP_IDS.lionsMane, companionSupplementId: SUPP_IDS.rhodiola, why: 'Cognitive performance and focus protocol — NGF support plus adaptogen.', strength: 'common', sortOrder: 1 },
  { id: 'cmp-lionsmane-omega3', supplementId: SUPP_IDS.lionsMane, companionSupplementId: SUPP_IDS.omega3, why: 'Omega-3 DHA supports neuronal health alongside NGF stimulation.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-melatonin-mag', supplementId: SUPP_IDS.melatonin, companionSupplementId: SUPP_IDS.magnesium, why: 'Classic sleep protocol pairing — magnesium promotes GABA activity alongside melatonin.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-melatonin-ashwa', supplementId: SUPP_IDS.melatonin, companionSupplementId: SUPP_IDS.ashwagandha, why: 'Common nighttime stress + sleep stack.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-rhodiola-ashwa', supplementId: SUPP_IDS.rhodiola, companionSupplementId: SUPP_IDS.ashwagandha, why: 'Classic dual-adaptogen stack for HPA axis balance and stress resilience.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-collagen-vitc', supplementId: SUPP_IDS.collagen, companionSupplementId: SUPP_IDS.vitC, why: 'Vitamin C is essential for collagen cross-linking; pair for skin and joint protocols.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-collagen-omega3', supplementId: SUPP_IDS.collagen, companionSupplementId: SUPP_IDS.omega3, why: 'Omega-3 anti-inflammatory effects complement collagen joint support.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-boron-vitd', supplementId: SUPP_IDS.boron, companionSupplementId: SUPP_IDS.vitD3, why: 'Boron enhances mineral retention in bone-health protocols with vitamin D.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-boron-mag', supplementId: SUPP_IDS.boron, companionSupplementId: SUPP_IDS.magnesium, why: 'Common mineral stack for bone and hormonal health.', strength: 'common', sortOrder: 2 },
  { id: 'cmp-turkeyTail-lionsMane', supplementId: SUPP_IDS.turkeyTail, companionSupplementId: SUPP_IDS.lionsMane, why: 'Medicinal mushroom duo for immune + cognitive support.', strength: 'strong', sortOrder: 1 },
  { id: 'cmp-turkeyTail-rhodiola', supplementId: SUPP_IDS.turkeyTail, companionSupplementId: SUPP_IDS.rhodiola, why: 'Mushroom + adaptogen stack for immune resilience and endurance.', strength: 'common', sortOrder: 2 },
];
