import type { TrendingApiResponse } from './types';

const NOW = new Date('2026-04-12T12:00:00.000Z').toISOString();

export const MOCK_TRENDING_PAYLOAD: TrendingApiResponse = {
  generatedAt: NOW,
  trending: [
    {
      slug: 'creatine-monohydrate',
      name: 'Creatine Monohydrate',
      mentionCount: 47,
      deltaWeek: 12.4,
      sources: ['huberman', 'rhonda-patrick', 'r/Supplements', 'r/Nootropics'],
      lastSeen: NOW,
    },
    {
      slug: 'ashwagandha',
      name: 'Ashwagandha',
      mentionCount: 39,
      deltaWeek: 6.1,
      sources: ['huberman', 'r/Supplements', 'peter-attia'],
      lastSeen: NOW,
    },
    {
      slug: 'nmn',
      name: 'NMN',
      mentionCount: 31,
      deltaWeek: 23.0,
      sources: ['rhonda-patrick', 'bryan-johnson', 'r/Longevity'],
      lastSeen: NOW,
    },
    {
      slug: 'magnesium-glycinate',
      name: 'Magnesium Glycinate',
      mentionCount: 28,
      deltaWeek: 4.2,
      sources: ['huberman', 'r/Supplements'],
      lastSeen: NOW,
    },
    {
      slug: 'l-theanine',
      name: 'L-Theanine',
      mentionCount: 25,
      deltaWeek: -3.1,
      sources: ['huberman', 'r/Nootropics'],
      lastSeen: NOW,
    },
    {
      slug: 'fish-oil',
      name: 'Fish Oil (Omega-3)',
      mentionCount: 24,
      deltaWeek: 1.8,
      sources: ['rhonda-patrick', 'peter-attia', 'examine'],
      lastSeen: NOW,
    },
    {
      slug: 'rhodiola-rosea',
      name: 'Rhodiola Rosea',
      mentionCount: 19,
      deltaWeek: 14.7,
      sources: ['r/Nootropics', 'huberman'],
      lastSeen: NOW,
    },
    {
      slug: 'vitamin-d3',
      name: 'Vitamin D3',
      mentionCount: 18,
      deltaWeek: -1.2,
      sources: ['rhonda-patrick', 'examine'],
      lastSeen: NOW,
    },
    {
      slug: 'lions-mane',
      name: "Lion's Mane",
      mentionCount: 17,
      deltaWeek: 9.6,
      sources: ['r/Nootropics', 'huberman'],
      lastSeen: NOW,
    },
    {
      slug: 'taurine',
      name: 'Taurine',
      mentionCount: 16,
      deltaWeek: 18.4,
      sources: ['peter-attia', 'r/Supplements'],
      lastSeen: NOW,
    },
    {
      slug: 'berberine',
      name: 'Berberine',
      mentionCount: 14,
      deltaWeek: -8.3,
      sources: ['peter-attia', 'examine'],
      lastSeen: NOW,
    },
    {
      slug: 'tongkat-ali',
      name: 'Tongkat Ali',
      mentionCount: 12,
      deltaWeek: 27.5,
      sources: ['huberman', 'r/Supplements'],
      lastSeen: NOW,
    },
  ],
  mostPopular: [
    { slug: 'creatine-monohydrate', name: 'Creatine Monohydrate', score: 92.4, ytViews: 18_400_000, ytVideoCount: 312, redditPosts: 1840, amazonReviews: 124000, amazonBSR: 12 },
    { slug: 'ashwagandha', name: 'Ashwagandha', score: 88.1, ytViews: 11_200_000, ytVideoCount: 287, redditPosts: 1402, amazonReviews: 98200, amazonBSR: 31 },
    { slug: 'fish-oil', name: 'Fish Oil (Omega-3)', score: 85.7, ytViews: 9_800_000, ytVideoCount: 254, redditPosts: 980, amazonReviews: 210000, amazonBSR: 8 },
    { slug: 'magnesium-glycinate', name: 'Magnesium Glycinate', score: 84.2, ytViews: 7_300_000, ytVideoCount: 198, redditPosts: 1320, amazonReviews: 88500, amazonBSR: 19 },
    { slug: 'vitamin-d3', name: 'Vitamin D3', score: 83.6, ytViews: 6_900_000, ytVideoCount: 312, redditPosts: 760, amazonReviews: 156000, amazonBSR: 14 },
    { slug: 'l-theanine', name: 'L-Theanine', score: 79.1, ytViews: 4_100_000, ytVideoCount: 142, redditPosts: 1180, amazonReviews: 41200, amazonBSR: 47 },
    { slug: 'nmn', name: 'NMN', score: 76.8, ytViews: 3_400_000, ytVideoCount: 178, redditPosts: 920, amazonReviews: 18400, amazonBSR: 92 },
    { slug: 'lions-mane', name: "Lion's Mane", score: 75.3, ytViews: 2_900_000, ytVideoCount: 156, redditPosts: 870, amazonReviews: 32600, amazonBSR: 58 },
    { slug: 'rhodiola-rosea', name: 'Rhodiola Rosea', score: 71.2, ytViews: 1_700_000, ytVideoCount: 98, redditPosts: 540, amazonReviews: 22800, amazonBSR: 121 },
    { slug: 'taurine', name: 'Taurine', score: 70.6, ytViews: 1_600_000, ytVideoCount: 84, redditPosts: 460, amazonReviews: 19800, amazonBSR: 134 },
    { slug: 'berberine', name: 'Berberine', score: 69.4, ytViews: 1_500_000, ytVideoCount: 112, redditPosts: 410, amazonReviews: 28400, amazonBSR: 88 },
    { slug: 'tongkat-ali', name: 'Tongkat Ali', score: 64.8, ytViews: 920_000, ytVideoCount: 67, redditPosts: 380, amazonReviews: 14200, amazonBSR: 162 },
  ],
};
